import { ArrowRight, Brain, BookOpenCheck, HardHat, Layers3 } from 'lucide-react';

export function PulseOSLanding() {
  return <main className="min-h-screen bg-softgray px-4 py-6 sm:px-6 sm:py-10">
    <section className="relative mx-auto max-w-6xl overflow-hidden rounded-3xl bg-navy-950 p-7 text-white shadow-2xl sm:p-12">
      <div className="absolute inset-0 bg-grid-dark bg-grid opacity-20" />
      <div className="relative">
        <div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-gold-500 text-navy-950"><Layers3 className="h-5 w-5" /></span><div><p className="text-sm font-bold tracking-wide">PulseOS</p><p className="text-xs text-gold-300">One system for workforce readiness and learning design</p></div></div>
        <div className="mt-12 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-gold-300">Build the work. Build the learning.</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-6xl">Every course can use UbD and learner variability intelligence.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-300">Start with workforce requirements when needed, then build the course in the same UbD framework—with LVI available for neurodivergent and neurotypical learners alike.</p></div>
        <div className="mt-10 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">
          <a href="/workforce" className="group rounded-2xl border border-white/15 bg-white/5 p-7 transition hover:-translate-y-1 hover:border-gold-400 hover:bg-white/10 hover:shadow-xl"><div className="flex items-start justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gold-500 text-navy-950"><HardHat className="h-6 w-6" /></span><ArrowRight className="h-5 w-5 text-gold-300 transition group-hover:translate-x-1" /></div><p className="mt-8 text-xs font-bold uppercase tracking-wider text-gold-300">When the job comes first</p><h2 className="mt-2 text-2xl font-bold">Workforce Intelligence</h2><p className="mt-3 text-sm leading-6 text-slate-300">Define competencies, map roles, validate evidence, and use the results to inform a course.</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-white">Open Workforce Intelligence <ArrowRight className="h-4 w-4" /></span></a>
          <article className="rounded-2xl border-2 border-gold-400 bg-gold-500 p-7 text-navy-950"><div className="flex items-start justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-navy-950 text-gold-400"><BookOpenCheck className="h-6 w-6" /></span><Brain className="h-5 w-5" /></div><p className="mt-8 text-xs font-bold uppercase tracking-wider text-navy-800">For every course</p><h2 className="mt-2 text-2xl font-bold">UbD Course Builder</h2><p className="mt-3 text-sm leading-6 text-navy-800">Build desired results, evidence, and the learning plan in one course workspace. Add LVI to design for learner variability from the start.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><a href="/course-builder" className="rounded-xl bg-navy-950 px-4 py-3 text-center text-sm font-bold text-white transition hover:bg-navy-800">Start a UbD course</a><a href="/learning-intelligence/lvi" className="rounded-xl border border-navy-900 bg-gold-400 px-4 py-3 text-center text-sm font-bold text-navy-950 transition hover:bg-gold-300">Start with LVI</a></div><p className="mt-4 text-xs font-semibold text-navy-800">Both paths continue to the same UbD course builder.</p></article>
        </div>
        <div className="mt-8 flex flex-wrap items-center gap-3 text-sm text-slate-300"><BookOpenCheck className="h-4 w-4 text-gold-300" /><span>UbD is the course framework. LVI is a design layer within it—not a separate kind of course.</span></div>
      </div>
    </section>
  </main>;
}
